
import { Event, Category, City, Organizer } from './types';

export const featuredCategories: Category[] = [
  { name: 'Ras Garba', events: '20 Events', icon: 'disc', color: 'bg-orange-500' },
  { name: 'Festival', events: '19 Events', icon: 'sparkles', color: 'bg-purple-500' },
  { name: 'Music', events: '9 Events', icon: 'music', color: 'bg-blue-500' },
  { name: 'Dance', events: '7 Events', icon: 'user', color: 'bg-pink-500' },
  { name: 'Food & Drink', events: '9 Events', icon: 'utensils', color: 'bg-red-500' },
  { name: 'Celebrity', events: '11 Events', icon: 'star', color: 'bg-yellow-500' },
];

export const carouselEvents: Event[] = [
  {
    title: 'Vivid Sydney 2026 - Light, Music & Ideas',
    date: 'MAY 22, 2026',
    day: 'Friday',
    time: '6:00 PM - 11:00 PM',
    category: 'Festival',
    price: 'Free',
    city: 'Sydney',
    location: 'Circular Quay',
    description: 'The world\'s largest festival of light, music and ideas return to Sydney.',
    image: '/img/hero-cover.jpg',
    link: '#'
  },
  {
    title: 'Australian Open 2026 - Finals Weekend',
    date: 'JAN 31, 2026',
    day: 'Saturday',
    time: '10:00 AM - 11:30 PM',
    category: 'Sports',
    price: '$150.00',
    city: 'Melbourne',
    location: 'Rod Laver Arena',
    description: 'Witness history at the first Grand Slam of the year in Melbourne.',
    image: '/img/anmolbrisbane.jpg',
    link: '#'
  },
  {
    title: 'Brisbane Comedy Festival 2026',
    date: 'APR 15, 2026',
    day: 'Wednesday',
    time: '7:00 PM - 10:30 PM',
    category: 'Comedy',
    price: '$45.00',
    city: 'Brisbane',
    location: 'Brisbane Powerhouse',
    description: 'A month-long celebration of laughter featuring local and international acts.',
    image: '/img/baithak3-1.jpg',
    link: '#'
  }
];

export const upcomingEvents: Event[] = [
  {
    title: 'Standup Comedy by Gaurav Gupta Live in Perth - 2026',
    date: 'MAY 22, 2026',
    day: 'FRI',
    time: '7:00 PM',
    category: 'Comedy',
    price: '$59.00',
    city: 'Perth',
    location: 'Crown Theatre',
    description: '',
    image: '/img/gaurav-gupta.jpg',
    slug: 'gaurav-gupta-perth-2026',
    link: '/event/gaurav-gupta-perth-2026',
    regular_price: '$59.00',
    early_bird: '$49.00',
  },
  {
    title: 'ANMOL MAGIC\'S Out Of This World - Live In Brisbane',
    date: 'FEB 27, 2026',
    day: 'FRI',
    time: '7:00 PM',
    category: 'Magic Show',
    price: '$35.00',
    city: 'Brisbane',
    location: 'SunPAC',
    description: '',
    image: '/img/anmolbrisbane.jpg',
    slug: 'anmol-magic-brisbane-2026',
    link: '/event/anmol-magic-brisbane-2026',
    regular_price: '$35.00',
    early_bird: '$25.00',
  },
  {
    title: 'Sur Aur Sitaar - An Evening With Ustad Shujaat Khan in Sydney',
    date: 'MAR 06, 2026',
    day: 'FRI',
    time: '7:00 PM',
    category: 'Classical Music',
    price: '$59.00',
    city: 'Sydney',
    location: 'State Theatre',
    description: '',
    image: '/img/ustad-shujaat-khan.jpg',
    slug: 'ustad-shujaat-khan-sydney-2026',
    link: '/event/ustad-shujaat-khan-sydney-2026',
  },
  {
    title: 'Chinmaya Hanuman Festival 2026',
    date: 'APR 03, 2026',
    day: 'FRI',
    time: '7:00 PM',
    category: 'Festival',
    price: '$5.00',
    city: 'Melbourne',
    location: 'Melbourne Town Hall',
    description: '',
    image: '/img/chinmaya-mission.jpg',
    slug: 'chinmaya-hanuman-festival-2026',
    link: '/event/chinmaya-hanuman-festival-2026',
  },
  {
    title: 'Standup Comedy by Gaurav Gupta Live in Adelaide - 2026',
    date: 'MAY 29, 2026',
    day: 'FRI',
    time: '7:00 PM',
    category: 'Comedy',
    price: '$59.00',
    city: 'Adelaide',
    location: 'Woodville Town Hall',
    description: '',
    image: '/img/gg-adl-2026.jpg',
    slug: 'gaurav-gupta-adelaide-2026',
    link: '/event/gaurav-gupta-adelaide-2026',
  },
  {
    title: 'Harsh Gujral Live in Melbourne 2026',
    date: 'JUL 12, 2026',
    day: 'SUN',
    time: '6:00 PM',
    category: 'Comedy',
    price: '$49.00',
    city: 'Melbourne',
    location: 'Palais Theatre',
    description: '',
    image: '/img/harsh-mel.jpg',
    slug: 'harsh-gujral-melbourne-2026',
    link: '/event/harsh-gujral-melbourne-2026',
  },
  {
    title: 'ANMOL MAGIC\'S Out Of This World - Live In Perth',
    date: 'MAR 01, 2026',
    day: 'SUN',
    time: '6:00 PM',
    category: 'Magic Show',
    price: '$25.00',
    city: 'Perth',
    location: 'Mandurah Performing Arts Centre',
    description: '',
    image: '/img/anmolmagic.jpg',
    slug: 'anmol-magic-perth-2026',
    link: '/event/anmol-magic-perth-2026',
  },
  {
    title: 'Baithak 3 Live in Sydney 2026',
    date: 'MAR 07, 2026',
    day: 'SAT',
    time: '7:00 PM',
    category: 'Music',
    price: '$19.50',
    city: 'Sydney',
    location: 'Science Theatre UNSW',
    description: '',
    image: '/img/baithak3-1.jpg',
    slug: 'baithak-3-sydney-2026',
    link: '/event/baithak-3-sydney-2026',
  }
];

export const topCities: City[] = [
  { name: 'Melbourne', events: 80, image: '/img/melbourne.jpg', link: '#' },
  { name: 'Sydney', events: 8, image: '/img/sydney.jpg', link: '#' },
  { name: 'Perth', events: 9, image: '/img/perth.jpg', link: '#' },
  { name: 'Adelaide', events: 5, image: '/img/adelaide.jpg', link: '#' },
  { name: 'Brisbane', events: 2, image: '/img/brisbane.jpg', link: '#' },
  { name: 'Canberra', events: 0, image: '/img/canberra.jpg', link: '#' },
  { name: 'Darwin', events: 0, image: '/img/darwin.jpg', link: '#' },
  { name: 'Hobart', events: 0, image: '/img/hobart.jpg', link: '#' },
];

export const pastEvents: Event[] = [
    {
        title: 'Standup Comedy by Gaurav Gupta Live in Perth - 2023', 
        date: 'MAY 22, 2023', 
        day: 'FRI',
        time: '7:00 PM',
        category: 'Comedy',
        price: 'Ended',
        city: 'Perth',
        location: '',
        description: '',
        image: '/img/gaurav-gupta.jpg',
        link: '#'
    },
    {
        title: 'ANMOL MAGIC\'S Out Of This World - Live In Brisbane', 
        date: 'FEB 27, 2023', 
        day: 'FRI',
        time: '7:00 PM',
        category: 'Magic Show',
        price: 'Ended',
        city: 'Brisbane',
        location: '',
        description: '',
        image: '/img/anmolbrisbane.jpg',
        link: '#'
    },
    {
        title: 'Sur Aur Sitaar - An Evening With Ustad Shujaat Khan in Sydney', 
        date: 'MAR 06, 2023', 
        day: 'FRI',
        time: '7:00 PM',
        category: 'Classical Music',
        price: 'Ended', 
        city: 'Sydney',
        location: '',
        description: '',
        image: '/img/ustad-shujaat-khan.jpg',
        link: '#'
    },
    {
        title: 'Chinmaya Hanuman Festival 2023', 
        date: 'APR 03, 2023', 
        day: 'FRI',
        time: '7:00 PM',
        category: 'Festival',
        price: 'Ended', 
        city: 'Melbourne',
        location: '',
        description: '',
        image: '/img/chinmaya-mission.jpg',
        link: '#'
    },
    {
        title: 'Standup Comedy by Gaurav Gupta Live in Adelaide - 2023', 
        date: 'MAY 29, 2023', 
        day: 'FRI',
        time: '7:00 PM',
        category: 'Comedy',
        price: 'Ended', 
        city: 'Adelaide',
        location: '',
        description: '',
        image: '/img/gg-adl-2026.jpg',
        link: '#'
    },
    {
        title: 'Harsh Gujral Live in Melbourne 2023', 
        date: 'JUL 12, 2023', 
        day: 'SUN',
        time: '6:00 PM',
        category: 'Comedy',
        price: 'Ended', 
        city: 'Melbourne',
        location: '',
        description: '',
        image: '/img/harsh-mel.jpg',
        link: '#'
    },
    {
        title: 'ANMOL MAGIC\'S Out Of This World - Live In Perth', 
        date: 'MAR 01, 2023', 
        day: 'SUN',
        time: '6:00 PM',
        category: 'Magic Show',
        price: 'Ended', 
        city: 'Perth',
        location: '',
        description: '',
        image: '/img/anmolmagic.jpg',
        link: '#'
    },
    {
        title: 'Baithak 3 Live in Sydney 2023', 
        date: 'MAR 07, 2023', 
        day: 'SAT',
        time: '7:00 PM',
        category: 'Music',
        price: 'Ended', 
        city: 'Sydney',
        location: '',
        description: '',
        image: '/img/baithak3-1.jpg',
        link: '#'
    }
];

export const organizer: Organizer = {
    name: 'Premier Tickets Events',
    logo: '/img/logo-dark.svg', // Placeholder
    bio: 'Premier Tickets is an Australian ticketing portal offering a seamless experience for organizers and attendees alike. We host massive events spanning comedy, festivals, and music across major Australian cities.',
    socials: {
        facebook: 'https://facebook.com',
        instagram: 'https://instagram.com',
        twitter: 'https://twitter.com',
        website: 'https://premiertickets.com.au'
    },
    total_events: 42,
    followers: '12.5k'
};
